import { DtoBuilder } from './dto-builder';
import { IIngredientListItemDto, IngredientId } from '../types';

export class IngredientListItemDtoBuilder extends DtoBuilder<IIngredientListItemDto> {
  protected getRequiredKeysMap(): Record<
    keyof IIngredientListItemDto,
    boolean
  > {
    return { id: true, name: true };
  }

  static prefilled(): IngredientListItemDtoBuilder {
    return new IngredientListItemDtoBuilder()
      .havingId('autogenerated')
      .named('Pomidor');
  }

  havingId(id: IngredientId | 'autogenerated'): this {
    return this.withProperty(
      'id',
      id === 'autogenerated' ? this.autoGeneratedId('ingredient-') : id
    );
  }

  named(name: string): this {
    return this.withProperty('name', name);
  }
}
