import { DtoBuilder } from './dto-builder';
import { IRecipeListItemDto, RecipeId } from '../types';

export class RecipeListItemDtoBuilder extends DtoBuilder<IRecipeListItemDto> {
  protected getRequiredKeysMap(): Record<keyof IRecipeListItemDto, boolean> {
    return {
      id: true,
      name: true,
      description: true,
      preparationTime: true,
      portions: true,
    };
  }

  static prefilled(): RecipeListItemDtoBuilder {
    return new RecipeListItemDtoBuilder()
      .havingId('autogenerated')
      .named('Pizza margarita')
      .described('Królowa gatunku, czyli margherita!')
      .havingPreparationTime(45 * 60)
      .havingPortions(4);
  }

  havingId(id: RecipeId | 'autogenerated'): this {
    return this.withProperty(
      'id',
      id === 'autogenerated' ? this.autoGeneratedId('recipe-category-') : id
    );
  }

  named(name: string): this {
    return this.withProperty('name', name);
  }

  described(description: string): this {
    return this.withProperty('description', description);
  }

  havingPreparationTime(preparationTime: number): this {
    return this.withProperty('preparationTime', preparationTime);
  }

  havingPortions(portions: number): this {
    return this.withProperty('portions', portions);
  }
}
