import { DtoBuilder } from './dto-builder';
import { IRecipeCategoryListItemDto, RecipeCategoryId } from '../types';

export class RecipeCategoryListItemDtoBuilder extends DtoBuilder<IRecipeCategoryListItemDto> {
  protected getRequiredKeysMap(): Record<
    keyof IRecipeCategoryListItemDto,
    boolean
  > {
    return { id: true, name: true };
  }

  static empty(): RecipeCategoryListItemDtoBuilder {
    return new RecipeCategoryListItemDtoBuilder();
  }

  static prefilled(): RecipeCategoryListItemDtoBuilder {
    return RecipeCategoryListItemDtoBuilder.empty()
      .havingId('autogenerated')
      .named('Kuchnia Włoska');
  }

  havingId(id: RecipeCategoryId | 'autogenerated'): this {
    return this.withProperty(
      'id',
      id === 'autogenerated' ? this.autoGeneratedId('recipe-category-') : id
    );
  }

  named(name: string): this {
    return this.withProperty('name', name);
  }
}
