import { DtoBuilder } from './dto-builder';
import { IReviewListItemDto, ReviewId } from '../types/reviews';
import { RecipeId } from '../types';

export class ReviewListItemDtoBuilder extends DtoBuilder<IReviewListItemDto> {
  protected getRequiredKeysMap(): Record<keyof IReviewListItemDto, boolean> {
    return {
      id: true,
      recipe_id: true,
      review_value: true,
    };
  }

  static empty(): ReviewListItemDtoBuilder {
    return new ReviewListItemDtoBuilder();
  }

  static prefilled(): ReviewListItemDtoBuilder {
    return ReviewListItemDtoBuilder.empty()
      .havingId('autogenerated')
      .withRecipeId('autogenerated')
      .withReviewValue(5);
  }

  havingId(id: ReviewId | 'autogenerated'): this {
    return this.withProperty(
      'id',
      id === 'autogenerated' ? this.autoGeneratedId('review-') : id
    );
  }

  withRecipeId(recipeId: RecipeId | 'autogenerated'): this {
    return this.withProperty(
      'recipe_id',
      recipeId === 'autogenerated' ? this.autoGeneratedId('recipe-') : recipeId
    );
  }

  withReviewValue(reviewValue: number): this {
    return this.withProperty('review_value', reviewValue);
  }
}
