import { DtoBuilder } from './dto-builder';
import { IAddReviewDto } from '../types/reviews';
import { RecipeId } from '../types';

export class AddReviewDtoBuilder extends DtoBuilder<IAddReviewDto> {
  protected getRequiredKeysMap(): Record<keyof IAddReviewDto, boolean> {
    return {
      recipe_id: true,
      review_value: true,
    };
  }

  static empty(): AddReviewDtoBuilder {
    return new AddReviewDtoBuilder();
  }

  static prefilled(): AddReviewDtoBuilder {
    return AddReviewDtoBuilder.empty()
      .withRecipeId('autogenerated')
      .withReviewValue(5);
  }

  withRecipeId(recipeId: RecipeId | 'autogenerated'): this {
    return this.withProperty(
      'recipe_id',
      recipeId === 'autogenerated' ? this.autoGeneratedId('recipe-') : recipeId
    );
  }

  withReviewValue(reviewValue: number): this {
    return this.withProperty('review_value', reviewValue);
  }
}
