import '@fe/styles/globals.css';
import 'antd-mobile/es/global/global.css';
import type { AppProps } from 'next/app';
import { env, headTitle } from '@fe/utils';
import Head from 'next/head';
import { Roboto } from 'next/font/google';
import classNames from 'classnames';
import { AppProvider } from '@fe/AppProvider';
import { Amplify } from '@aws-amplify/core';
import dynamic from 'next/dynamic';

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  variable: '--adm-font-family',
});

Amplify.configure({
  Auth: env().cognito,
  ssr: true,
});

const NavigationBar = dynamic(() => import('@fe/application/NavigationBar'));
const TopBar = dynamic(() => import('@fe/application/TopBar'));

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>{headTitle()}</title>

        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />

        <style>
          {`
          :root:root {
            --adm-font-family: ${roboto.style.fontFamily}
          }
          `}
        </style>
      </Head>

      <AppProvider
        dehydratedReactQueryState={pageProps.dehydratedReactQueryState}
        isPublicPage={!!pageProps.isPublicPage}
      >
        <div
          className={classNames('pb-16 flex flex-col justify-between md:pl-44')}
        >
          <TopBar className="grow-0 pt-4" />

          <div className="grow overflow-auto p-4">
            <Component {...pageProps} />
          </div>

          <NavigationBar className="fixed left-0 right-0 bottom-0 bg-white" />
        </div>
      </AppProvider>
    </>
  );
}
