@startuml
object Recipe  {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar(20) |
    | cuisine_type_id | uuid | **FK** |
}

object RecipeInstructionStep {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id | uuid | **PK** |
    | instruction | varchar(100) |
    | timer | integer |
    | recipie_id | uuid | **FK** |
}

object Ingredient {
  <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar(20) |
    | quantity | integer |
    | unit | varchar(20) |
    | food_item_id | uuid| **FK** |
    | recipie_id | uuid | **FK** |
}

object FoodItem {
  <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar(20) |
    | food_item_category_id | uuid | **FK** |
}

object FoodItemCategory {
  <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar(20) |
}

object CuisineType {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar(20) |
}

object RecipeCategory {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar(20) |
}

object Recipe_RecipeCategory {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | recipe_id | uuid | **PK FK** |
    | recipe_category_id | uuid | **PK FK** |
}

object User {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
}

object UserFavouriteRecipe {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | user_id |  uuid | **PK FK** |
    | dish_id |  uuid | **PK FK** |
}

object Review {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | user_id | uuid | **PK FK** |
    | dish_id | uuid | **PK FK** |
    | created_at | timestamp | |
    | review_value | integer | |
}

object ShoppingList {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id | uuid | **PK** |
    | user_id | uuid | **FK** |
    | food_item_id | uuid | **FK** |
    | quantity | decimal | |
    | unit | varchar(20) | |
    | completed | boolean | |
}

Recipe -down-{ Ingredient
RecipeInstructionStep }-- Recipe
Ingredient }-right- FoodItem
FoodItem }-- FoodItemCategory
Recipe }-up- CuisineType
Recipe -left-{ Recipe_RecipeCategory
Recipe_RecipeCategory }-up- RecipeCategory
Recipe -right-{ UserFavouriteRecipe
UserFavouriteRecipe }-right- User
Recipe -up-{ Review
Review }-down- User
User -- ShoppingList
ShoppingList -left-{ FoodItem
@enduml