@startuml
object recipes  {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id | uuid | **PK** |
    | name | varchar |
    | description | varchar |
    | preparation_time | integer |
    | portions | integer |
    | instructions | jsonb |
    | author_id | uuid | **FK** |
    | state | varchar |
    | difficulty | recipes_difficulty_enum |
    | review | numeric |
    | cover_image | varchar |
}

object recipe_ingredients {
  <#F1F1F1,#F1F1F1>|= |= |= |
    | recipie_id | uuid | **PK** **FK** |
    | ingredient_id | uuid | **PK** **FK** |
    | quantity | numeric |
    | unit | varchar |
}


object ingredients {
  <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar |
}

object categories {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | name | varchar |
    | type | categories_type_enum |
}

object recipe_categories {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | recipe_id | uuid | **PK FK** |
    | category_id | uuid | **PK FK** |
}

object users {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id |  uuid | **PK** |
    | status |  varchar |
}

object users_favourite_recipes {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | user_id |  uuid | **PK FK** |
    | recipe_id |  uuid | **PK FK** |
}

object reviews {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | recipe_id | uuid | **PK FK** |
    | reviewer_id | uuid | **PK FK** |
    | created_at | timestamp | |
    | value | numeric | |
}

object shopping_list {
    <#F1F1F1,#F1F1F1>|= |= |= |
    | id | uuid | **PK** |
    | user_id | uuid | **FK** |
    | ingredient_id | uuid | **FK** |
    | quantity | numeric |
    | unit | varchar |
    | completed | boolean |
}

recipes -down-{ recipe_ingredients
recipe_ingredients }-right- ingredients
recipes -left-{ recipe_categories
recipe_categories }-up- categories
recipes -right-{ users_favourite_recipes
users_favourite_recipes }-right- users
recipes -up-{ reviews
reviews }-down- users
users -- shopping_list
shopping_list -left-{ ingredients
@enduml