@startuml
left to right direction

actor "Użytkownik" as user

rectangle IAM {
    usecase "Rejestracja" as iam_register
    usecase "Logowanie" as iam_login
    usecase "Przypomnienie\nhasła" as iam_forgot_password
    usecase "Wylogowanie" as iam_logout
    usecase "Zmiana hasła" as iam_password_change
    usecase "Zmiana adresu\nemail" as iam_email_change
    usecase "Podgląd profilu" as iam_me_details
    usecase "Modyfikacja profilu" as iam_me_edit
}

usecase "Wyświetlanie popularnych\nprzepisów" as home_popular_recipes
usecase "Wyświetlanie popularnych\nkategorii" as home_popular_categories
usecase "Wyświetlanie własnych\nprzepisów" as home_my_recipes

usecase "Wyświetlanie przepisów" as recipes
usecase "Filtrowanie na bazie\nskładników" as filter_recipes_by_ingredients
usecase "Filtrowanie na bazie\ninnych filtrów" as filter_recipes_by_filters

usecase "Wyświetlanie szczegółów\nprzepisu" as recipe_details
usecase "Dostosowywanie ilości\nskładników przepisu" as recipe_details_adjust_quantity
usecase "Ocenianie przepisu" as recipe_details_rate
usecase "Wspomaganie gotowania" as recipe_details_cooking_mode

usecase "Dodawanie przepisu do\nulubionych" as add_recipe_to_favourite
usecase "Usuwanie przepisu z\nulubionych" as remove_recipe_from_favourite
usecase "Wyświetlanie ulubionych\nprzepisów" as favourite_recipes

usecase "Dodawanie składników\nprzepisu do listy zakupów" as add_recipe_ingredients_to_shopping_list
usecase "Wyświetlenie listy\nzakupów" as shopping_list
usecase "Czyszczenie listy\nzakupów" as shopping_list_clear
usecase "Modyfikowanie listy\nzakupów" as shopping_list_edit
usecase "Ukończenie elementu\nz listy zakupów" as shopping_list_complete

usecase "Dodawanie przepisu" as add_recipe
usecase "Modyfikowanie\nprzepisu" as edit_recipe
usecase "Usuwanie\nprzepisu" as delete_recipe
usecase "Publikowanie\nprzepisu" as publish_recipe

user -- iam_register
user -- iam_login
iam_register <-- iam_forgot_password : <<include>>
iam_login <-- iam_logout : <<include>>
iam_login <-- iam_password_change : <<include>>
iam_login <-- iam_email_change : <<include>>
iam_login <-- iam_me_details : <<include>>
iam_login <-- iam_me_edit : <<include>>

user -- home_popular_recipes
user -- home_popular_categories
user -- home_my_recipes

user -- recipes
recipes <-- filter_recipes_by_ingredients : <<extends>>
recipes <-- filter_recipes_by_filters  : <<extends>>


user -- recipe_details
recipe_details <-- recipe_details_adjust_quantity : <<include>>
recipe_details <-- recipe_details_rate : <<include>>
recipe_details <-- recipe_details_cooking_mode : <<include>>

user -- add_recipe_to_favourite
user -- remove_recipe_from_favourite
user -- favourite_recipes

user -- add_recipe_ingredients_to_shopping_list
user -- shopping_list
shopping_list <-- shopping_list_clear : <<include>>
shopping_list <-- shopping_list_edit : <<include>>
shopping_list <-- shopping_list_complete : <<include>>

user -- add_recipe
add_recipe <-- publish_recipe : <<include>>
add_recipe <-- edit_recipe : <<include>>
add_recipe <-- delete_recipe : <<include>>
@enduml
