@startuml
left to right direction

actor "Niezalogowany\n   użytkownik" as anonymous_user
actor "Zalogowany\n użytkownik" as logged_in_user

rectangle IAM {
    usecase "Rejestracja" as iam_register
    usecase "Logowanie" as iam_login
}

usecase "Wyświetlanie popularnych\nprzepisów" as home_popular_recipes
usecase "Wyświetlanie popularnych\nkategorii" as home_popular_categories
usecase "Wyświetlanie własnych\nprzepisów" as home_my_recipes

usecase "Wyświetlanie przepisów\nna bazie składników" as recipes_by_ingredients
usecase "Wyświetlanie przepisów\nna bazie filtrów" as recipes_by_filters

usecase "Wyświetlanie szczegółów\nprzepisu" as recipe_details
usecase "Dostosowywanie ilości\nskładników przepisu" as recipe_details_adjust_quantity
usecase "Ocenianie przepisu" as recipe_details_rate
usecase "Tryb gotowania" as recipe_details_cooking_mode

usecase "Dodawanie przepisu do\nulubionych" as add_recipe_to_favourite
usecase "Usuwanie przepisu z\nulubionych" as remove_recipe_from_favourite
usecase "Wyświetlanie ulubionych\nprzepisów" as favourite_recipes

usecase "Dodawanie składników\nprzepisu do listy zakupów" as add_recipe_ingredients_to_shopping_list
usecase "Wyświetlenie listy\nzakupów" as shopping_list
usecase "Czyszczenie listy\nzakupów" as shopping_list_clear
usecase "Modyfikowanie listy\nzakupów" as shopping_list_edit
usecase "Ukończenie elementu\nz listy zakupów" as shopping_list_complete

usecase "Dodawanie przepisu" as add_recipe
usecase "Modyfikowanie\nprzepisu" as edit_recipe
usecase "Usuwanie\nprzepisu" as delete_recipe
usecase "Publikowanie\nprzepisu" as publish_recipe

anonymous_user <|-right- logged_in_user

anonymous_user -- iam_register
anonymous_user -- iam_login

logged_in_user -- home_popular_recipes
logged_in_user -- home_popular_categories
logged_in_user -- home_my_recipes

logged_in_user -- recipes_by_ingredients
logged_in_user -- recipes_by_filters

logged_in_user -- recipe_details
recipe_details <-- recipe_details_adjust_quantity : <<include>>
recipe_details <-- recipe_details_rate : <<include>>
recipe_details <-- recipe_details_cooking_mode : <<include>>

logged_in_user -- add_recipe_to_favourite
logged_in_user -- remove_recipe_from_favourite
logged_in_user -- favourite_recipes

logged_in_user -- add_recipe_ingredients_to_shopping_list
logged_in_user -- shopping_list
shopping_list -- shopping_list_clear : <<include>>
shopping_list -- shopping_list_edit : <<include>>
shopping_list -- shopping_list_complete : <<include>>

logged_in_user -- add_recipe
add_recipe -- publish_recipe : <<include>>
add_recipe -- edit_recipe : <<include>>
add_recipe -- delete_recipe : <<include>>
@enduml
